---
title: "PDS Data Munging"
author: "Paul"
date: "2023-10-05"
output: pdf_document
---

```{r}
library(ncdf4)
library(DataExplorer)
library(plotly)
library(tidyverse)
library(data.table)
```


# Loading Data

## 1-min Flux Summary

```{r}
# Set the directory path
directory_path <- "/Users/welpp/Desktop/Practical Data Science/Data/Data Main/1minSum"

# Get a list of all files in the directory
file_list <- list.files(path = directory_path)

# Print the list of file names
print(file_list)
```

```{r}
# Open ncdf4 data
for(i in 13:18){
  data_name <- paste0("GOES",i)
  data_path <- paste0(directory_path,"/",file_list[i-7])
  assign(data_name, nc_open(data_path))
}
```


```{r}
## function for grabbing 1min summary
make_df_1min <- function(file){
  time1 <- file$dim$time$vals
  time <- as.POSIXct(time1, origin="2000-01-01", tz="UTC")
  
  var_names <- names(file$var)[c(1,4)]
  
  for (i in var_names){
    name <- paste("", i, sep = "")
    assign(name, ncvar_get(file, varid = i))
  }
  
  
  file_df <- data.frame(lapply(mget(var_names), as.vector))
  file_df <- cbind(time, file_df)
  
  return(file_df)
}
```

```{r}
df_goes_13 <- make_df_1min(GOES13)
df_goes_14 <- make_df_1min(GOES14)
df_goes_15 <- make_df_1min(GOES15)
df_goes_16 <- make_df_1min(GOES16)
df_goes_17 <- make_df_1min(GOES17)
df_goes_18 <- make_df_1min(GOES18)

# View(df_goes_13)
# View(df_goes_14)
# View(df_goes_15)
# View(df_goes_16)
# View(df_goes_17)
# View(df_goes_18)
```


## Flare Summary

```{r}
# Set the directory path
directory_path <- "/Users/welpp/Desktop/Practical Data Science/Data/Data Main/FlareSum"

# Get a list of all files in the directory
file_list <- list.files(path = directory_path)

# Print the list of file names
print(file_list)
```

```{r}
# Open ncdf4 data
for(i in 13:18){
  data_name <- paste0("FlareGOES",i)
  data_path <- paste0(directory_path,"/",file_list[i-12])
  assign(data_name, nc_open(data_path))
}
```


```{r}
## function for grabbing flare summary
make_df_flare <- function(file){
  time1 <- file$dim$time$vals
  time <- as.POSIXct(time1, origin="2000-01-01", tz="UTC")
  
  var_names <- names(file$var)[c(1,2,4,6)]
  
  for (i in var_names){
    name <- paste("", i, sep = "")
    assign(name, ncvar_get(file, varid = i))
  }
  
  
  file_df <- data.frame(lapply(mget(var_names), as.vector))
  file_df <- cbind(time, file_df)
  
  return(file_df)
}
```

```{r}
df_flare_13 <- make_df_flare(FlareGOES13)
df_flare_14 <- make_df_flare(FlareGOES14)
df_flare_15 <- make_df_flare(FlareGOES15)
df_flare_16 <- make_df_flare(FlareGOES16)
df_flare_17 <- make_df_flare(FlareGOES17)
df_flare_18 <- make_df_flare(FlareGOES18)

# View(df_flare_13)
# View(df_flare_14)
# View(df_flare_15)
# View(df_flare_16)
# View(df_flare_17)
# View(df_flare_18)
```


## Solar Flare Peak Selection

```{r}
df_flare_13_peaks <- df_flare_13 %>% filter(status == "EVENT_PEAK")
df_flare_14_peaks <- df_flare_14 %>% filter(status == "EVENT_PEAK")
df_flare_15_peaks <- df_flare_15 %>% filter(status == "EVENT_PEAK")
df_flare_16_peaks <- df_flare_16 %>% filter(status == "EVENT_PEAK")
df_flare_17_peaks <- df_flare_17 %>% filter(status == "EVENT_PEAK")
df_flare_18_peaks <- df_flare_18 %>% filter(status == "EVENT_PEAK")
```

# Merging Solar Data with Peaks

## Merging for each Satellites

```{r}
merge_df_13_peaks <- left_join(na.omit(df_goes_13, cols = "xrsa_flux"), 
                               df_flare_13_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 13) %>%
  select(-xrsb_flux.y, -flare_counter) %>% rename(xrsb_flux = "xrsb_flux.x")

merge_df_14_peaks <- left_join(na.omit(df_goes_14, cols = "xrsa_flux"), 
                               df_flare_14_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 14) %>%
  select(-xrsb_flux.y, -flare_counter) %>% rename(xrsb_flux = "xrsb_flux.x")

merge_df_15_peaks <- left_join(na.omit(df_goes_15, cols = "xrsa_flux"), 
                               df_flare_15_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 15) %>%
  select(-xrsb_flux.y, -flare_counter) %>% rename(xrsb_flux = "xrsb_flux.x")

merge_df_16_peaks <- left_join(na.omit(df_goes_16, cols = "xrsa_flux"),
                               df_flare_16_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 16) %>%
  select(-xrsb_flux.y, -flare_id) %>% rename(xrsb_flux = "xrsb_flux.x")

merge_df_17_peaks <- left_join(na.omit(df_goes_17, cols = "xrsa_flux"),
                               df_flare_17_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 17) %>%
  select(-xrsb_flux.y, -flare_id) %>% rename(xrsb_flux = "xrsb_flux.x")

merge_df_18_peaks <- left_join(na.omit(df_goes_18, cols = "xrsa_flux"),
                               df_flare_18_peaks, 
                               by = join_by(time)) %>% mutate(Sat = 18) %>%
  select(-xrsb_flux.y, -flare_id) %>% rename(xrsb_flux = "xrsb_flux.x")

```


## Merging all Satellites

```{r}
merge_list <-  list(merge_df_18_peaks, merge_df_17_peaks, merge_df_16_peaks, 
                    merge_df_15_peaks, merge_df_14_peaks, merge_df_13_peaks)

df_merge_peaks <- do.call(rbind, merge_list)
duplicate_times <- which(duplicated(df_merge_peaks$time))
df_merge_peaks_final <- df_merge_peaks[-duplicate_times,] %>% arrange(time)
df_merge_peaks_final$status <- ifelse(!is.na(df_merge_peaks_final$status), 1, 0)
```

```{r}
# Write out 
fwrite(df_merge_peaks_final, "/Users/welpp/Desktop/Practical Data Science/Data/Data Main/goes_13to18.csv")
```



